from src.classical_controls.ascent_control import AscentControl
from src.classical_controls.flip_over_and_boostbackburn_control import FlipOverandBoostbackBurnControl
ascent_control = AscentControl()
ascent_control.run_closed_loop()

flip_over_and_boostbackburn_control = FlipOverandBoostbackBurnControl()
flip_over_and_boostbackburn_control.run_closed_loop()